In [1]:
import torch

In [4]:
X=torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [12]:
def tanh(x):
    return (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))

def sigmoid(x):
    return 1 / (1 + torch.exp(-x))

In [23]:
torch.manual_seed(1)
class NeuralNetwork(torch.nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(NeuralNetwork, self).__init__()
        self.hidden_layer = torch.nn.Linear(input_size, hidden_size)
        self.output_layer = torch.nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = self.hidden_layer(x)
        x = tanh(x)
        x = self.output_layer(x)
        x = sigmoid(x)
        return x

input_size = 3
hidden_size = 50
output_size = 1

model = NeuralNetwork(input_size, hidden_size, output_size)

X = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
output_tensor = model(X)

print(output_tensor)

tensor([[0.4892],
        [0.5566]], grad_fn=<MulBackward0>)


In [21]:
torch.manual_seed(190401069)
model = NeuralNetwork(input_size, hidden_size, output_size)

X = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
output_tensor = model(X)
print(output_tensor)

tensor([[0.4695],
        [0.4620]], grad_fn=<MulBackward0>)
